/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module htax(clk, rst_n, tx_data, tx_valid, tx_vc, tx_ready, rx_data, rx_valid);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [31:0] tx_data;
  wire [31:0] tx_data;
  input tx_valid;
  wire tx_valid;
  input [2:0] tx_vc;
  wire [2:0] tx_vc;
  output tx_ready;
  wire tx_ready;
  output [31:0] rx_data;
  wire [31:0] rx_data;
  output rx_valid;
  wire rx_valid;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire \credit_count[0] ;
  wire \credit_count[1] ;
  wire \credit_count[2] ;
  wire \credit_count[3] ;
  wire state;
  sky130_fd_sc_hd__inv_2 _054_ (
    .A(\credit_count[0] ),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_2 _055_ (
    .A(state),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_2 _056_ (
    .A(\credit_count[3] ),
    .Y(_040_)
  );
  sky130_fd_sc_hd__or4_2 _057_ (
    .A(\credit_count[0] ),
    .B(\credit_count[1] ),
    .C(\credit_count[2] ),
    .D(\credit_count[3] ),
    .X(_041_)
  );
  sky130_fd_sc_hd__and3_2 _058_ (
    .A(_039_),
    .B(rst_n),
    .C(_041_),
    .X(tx_ready)
  );
  sky130_fd_sc_hd__and2_2 _059_ (
    .A(tx_valid),
    .B(tx_ready),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _060_ (
    .A0(rx_data[0]),
    .A1(tx_data[0]),
    .S(_000_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _061_ (
    .A0(rx_data[1]),
    .A1(tx_data[1]),
    .S(_000_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _062_ (
    .A0(rx_data[2]),
    .A1(tx_data[2]),
    .S(_000_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _063_ (
    .A0(rx_data[3]),
    .A1(tx_data[3]),
    .S(_000_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _064_ (
    .A0(rx_data[4]),
    .A1(tx_data[4]),
    .S(_000_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _065_ (
    .A0(rx_data[5]),
    .A1(tx_data[5]),
    .S(_000_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _066_ (
    .A0(rx_data[6]),
    .A1(tx_data[6]),
    .S(_000_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _067_ (
    .A0(rx_data[7]),
    .A1(tx_data[7]),
    .S(_000_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _068_ (
    .A0(rx_data[8]),
    .A1(tx_data[8]),
    .S(_000_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _069_ (
    .A0(rx_data[9]),
    .A1(tx_data[9]),
    .S(_000_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _070_ (
    .A0(rx_data[10]),
    .A1(tx_data[10]),
    .S(_000_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _071_ (
    .A0(rx_data[11]),
    .A1(tx_data[11]),
    .S(_000_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _072_ (
    .A0(rx_data[12]),
    .A1(tx_data[12]),
    .S(_000_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _073_ (
    .A0(rx_data[13]),
    .A1(tx_data[13]),
    .S(_000_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _074_ (
    .A0(rx_data[14]),
    .A1(tx_data[14]),
    .S(_000_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _075_ (
    .A0(rx_data[15]),
    .A1(tx_data[15]),
    .S(_000_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _076_ (
    .A0(rx_data[16]),
    .A1(tx_data[16]),
    .S(_000_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _077_ (
    .A0(rx_data[17]),
    .A1(tx_data[17]),
    .S(_000_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _078_ (
    .A0(rx_data[18]),
    .A1(tx_data[18]),
    .S(_000_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _079_ (
    .A0(rx_data[19]),
    .A1(tx_data[19]),
    .S(_000_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _080_ (
    .A0(rx_data[20]),
    .A1(tx_data[20]),
    .S(_000_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _081_ (
    .A0(rx_data[21]),
    .A1(tx_data[21]),
    .S(_000_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _082_ (
    .A0(rx_data[22]),
    .A1(tx_data[22]),
    .S(_000_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _083_ (
    .A0(rx_data[23]),
    .A1(tx_data[23]),
    .S(_000_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _084_ (
    .A0(rx_data[24]),
    .A1(tx_data[24]),
    .S(_000_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _085_ (
    .A0(rx_data[25]),
    .A1(tx_data[25]),
    .S(_000_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _086_ (
    .A0(rx_data[26]),
    .A1(tx_data[26]),
    .S(_000_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _087_ (
    .A0(rx_data[27]),
    .A1(tx_data[27]),
    .S(_000_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _088_ (
    .A0(rx_data[28]),
    .A1(tx_data[28]),
    .S(_000_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _089_ (
    .A0(rx_data[29]),
    .A1(tx_data[29]),
    .S(_000_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _090_ (
    .A0(rx_data[30]),
    .A1(tx_data[30]),
    .S(_000_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _091_ (
    .A0(rx_data[31]),
    .A1(tx_data[31]),
    .S(_000_),
    .X(_032_)
  );
  sky130_fd_sc_hd__a21o_2 _092_ (
    .A1(_039_),
    .A2(rx_valid),
    .B1(_000_),
    .X(_033_)
  );
  sky130_fd_sc_hd__a21o_2 _093_ (
    .A1(state),
    .A2(_040_),
    .B1(_000_),
    .X(_042_)
  );
  sky130_fd_sc_hd__xnor2_2 _094_ (
    .A(_038_),
    .B(_042_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2b_2 _095_ (
    .A_N(state),
    .B(\credit_count[1] ),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_2 _096_ (
    .A(state),
    .B(\credit_count[1] ),
    .X(_044_)
  );
  sky130_fd_sc_hd__xnor2_2 _097_ (
    .A(\credit_count[0] ),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _098_ (
    .A0(\credit_count[1] ),
    .A1(_045_),
    .S(_042_),
    .X(_035_)
  );
  sky130_fd_sc_hd__o21a_2 _099_ (
    .A1(_038_),
    .A2(_044_),
    .B1(_043_),
    .X(_046_)
  );
  sky130_fd_sc_hd__and2_2 _100_ (
    .A(_039_),
    .B(\credit_count[2] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor2_2 _101_ (
    .A(_039_),
    .B(\credit_count[2] ),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_2 _102_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xnor2_2 _103_ (
    .A(_046_),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(\credit_count[2] ),
    .A1(_050_),
    .S(_042_),
    .X(_036_)
  );
  sky130_fd_sc_hd__xnor2_2 _105_ (
    .A(state),
    .B(\credit_count[3] ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o21ba_2 _106_ (
    .A1(_046_),
    .A2(_048_),
    .B1_N(_047_),
    .X(_052_)
  );
  sky130_fd_sc_hd__xnor2_2 _107_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _108_ (
    .A1_N(_040_),
    .A2_N(_000_),
    .B1(_042_),
    .B2(_053_),
    .X(_037_)
  );
  sky130_fd_sc_hd__dfrtp_2 _109_ (
    .CLK(clk),
    .D(_001_),
    .Q(rx_data[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _110_ (
    .CLK(clk),
    .D(_002_),
    .Q(rx_data[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _111_ (
    .CLK(clk),
    .D(_003_),
    .Q(rx_data[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _112_ (
    .CLK(clk),
    .D(_004_),
    .Q(rx_data[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _113_ (
    .CLK(clk),
    .D(_005_),
    .Q(rx_data[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _114_ (
    .CLK(clk),
    .D(_006_),
    .Q(rx_data[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _115_ (
    .CLK(clk),
    .D(_007_),
    .Q(rx_data[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _116_ (
    .CLK(clk),
    .D(_008_),
    .Q(rx_data[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _117_ (
    .CLK(clk),
    .D(_009_),
    .Q(rx_data[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _118_ (
    .CLK(clk),
    .D(_010_),
    .Q(rx_data[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _119_ (
    .CLK(clk),
    .D(_011_),
    .Q(rx_data[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _120_ (
    .CLK(clk),
    .D(_012_),
    .Q(rx_data[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _121_ (
    .CLK(clk),
    .D(_013_),
    .Q(rx_data[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _122_ (
    .CLK(clk),
    .D(_014_),
    .Q(rx_data[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _123_ (
    .CLK(clk),
    .D(_015_),
    .Q(rx_data[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _124_ (
    .CLK(clk),
    .D(_016_),
    .Q(rx_data[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _125_ (
    .CLK(clk),
    .D(_017_),
    .Q(rx_data[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _126_ (
    .CLK(clk),
    .D(_018_),
    .Q(rx_data[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _127_ (
    .CLK(clk),
    .D(_019_),
    .Q(rx_data[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _128_ (
    .CLK(clk),
    .D(_020_),
    .Q(rx_data[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _129_ (
    .CLK(clk),
    .D(_021_),
    .Q(rx_data[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _130_ (
    .CLK(clk),
    .D(_022_),
    .Q(rx_data[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _131_ (
    .CLK(clk),
    .D(_023_),
    .Q(rx_data[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _132_ (
    .CLK(clk),
    .D(_024_),
    .Q(rx_data[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _133_ (
    .CLK(clk),
    .D(_025_),
    .Q(rx_data[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _134_ (
    .CLK(clk),
    .D(_026_),
    .Q(rx_data[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _135_ (
    .CLK(clk),
    .D(_027_),
    .Q(rx_data[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _136_ (
    .CLK(clk),
    .D(_028_),
    .Q(rx_data[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _137_ (
    .CLK(clk),
    .D(_029_),
    .Q(rx_data[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _138_ (
    .CLK(clk),
    .D(_030_),
    .Q(rx_data[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _139_ (
    .CLK(clk),
    .D(_031_),
    .Q(rx_data[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _140_ (
    .CLK(clk),
    .D(_032_),
    .Q(rx_data[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _141_ (
    .CLK(clk),
    .D(_033_),
    .Q(rx_valid),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _142_ (
    .CLK(clk),
    .D(_034_),
    .Q(\credit_count[0] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _143_ (
    .CLK(clk),
    .D(_035_),
    .Q(\credit_count[1] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _144_ (
    .CLK(clk),
    .D(_036_),
    .Q(\credit_count[2] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _145_ (
    .CLK(clk),
    .D(_037_),
    .Q(\credit_count[3] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _146_ (
    .CLK(clk),
    .D(_000_),
    .Q(state),
    .RESET_B(rst_n)
  );
endmodule
