// Auto-generated by LibreLane
module htax(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input[31:0] tx_data,
  input tx_valid,
  input[2:0] tx_vc,
  output tx_ready,
  output[31:0] rx_data,
  output rx_valid
);
endmodule
